name: nhost_dart
publish_to: none
homepage: https://nhost.io
repository: https://github.com/nhost/nhost-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  path:
  dotenv: 3.0.0-nullsafety.0
