# This is used to establish tool dependencies, and is never published.
name: nhost_dart
publish_to: none
homepage: https://nhost.io
repository: https://github.com/nhost/nhost-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  dotenv: 3.0.0-nullsafety.0
  melos: 0.4.10+1
  path: ^1.0.0
