# This is a template that is used to produce package-specific workflows
#
# The reason we want package-specific workflows at all is so we can
#
# 1. Limit the workflow to only being triggered on changes to files on the
#    package's path, and that of its dependents
# 2. Display a package-specific testing badge (at the time of writing, you can't
#    request badges for matrix configurations)
#
# Instantiations of this template are produced by the Melos postbootstrap script
# which can be found in `melos.yaml`.

name: 'nhost_graphql_adapter: Test'
on:
  push:
  pull_request:
  schedule:
  # Run the quality job at 4am every day
  - cron: '0 4 * * *'

jobs:
  # Ensure that the package meets a suitably high pub.dev score
  score-package-quality:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # We test against several Flutter versions
        flutter_channel: [stable, beta]

    steps:
    - uses: actions/checkout@v2

    - run: .github/workflows/scripts/make-relative-pubspecs.sh

    - uses: axel-op/dart-package-analyzer@v3
      # Set an id for the current step, so we can reference it later
      id: analysis
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        relativePath: packages/nhost_graphql_adapter

    - name: Require analysis (near) perfection
      env:
        # "analysis" is the id set above
        TOTAL: ${{ steps.analysis.outputs.total }}
        TOTAL_MAX: ${{ steps.analysis.outputs.total_max }}
        CONVENTIONS: ${{ steps.analysis.outputs.conventions }}
        CONVENTIONS_MAX: ${{ steps.analysis.outputs.conventions_max }}
        PLATFORMS: ${{ steps.analysis.outputs.platforms }}
        PLATFORMS_MAX: ${{ steps.analysis.outputs.platforms_max }}
      run: |
        PERCENTAGE=$((( $TOTAL - $CONVENTIONS - $PLATFORMS ) * 100 / ( $TOTAL_MAX - $CONVENTIONS_MAX - $PLATFORMS_MAX )))
        if (( $PERCENTAGE < 100 ))
        then
          echo Score to low.
          exit 1
        fi

  # Analyzes, checks formatting, and tests the packages
  test-package:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # We test against several Flutter versions
        flutter_channel: [stable, beta]

    steps:
    - uses: actions/checkout@v2

    # Setup the flutter environment
    - name: Setup Dart/Flutter (specific version)
      uses: subosito/flutter-action@v1.4.0
      if: matrix.flutter_version != null
      with:
        flutter-version: ${{ matrix.flutter_version }}

    # Setup the flutter environment
    - name: Setup Dart/Flutter (specific channel)
      uses: subosito/flutter-action@v1.4.0
      if: matrix.flutter_version == null
      with:
        channel: ${{ matrix.flutter_channel }}

    # Get binary dependencies
    - name: Install tools
      run: |
        echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
        pub global activate junitreport
        pub global activate melos

    - name: Bootstrap packages
      run: melos bootstrap

    # Run analysis on all packages
    - name: Analyze Dart
      run: melos exec -- flutter analyze --congratulate

    # Run tests for package in question
    - name: Execute tests
      run: >
        melos exec --scope=nhost_graphql_adapter --
        'flutter test --no-pub --machine --coverage | tojunit
        > test-results.xml'

    # Report test results
    - name: Report test results
      uses: mikepenz/action-junit-report@v2
      with:
        check_name: 'Test results: nhost_graphql_adapter'
        report_paths: "packages/nhost_graphql_adapter/test-results.xml"
        github_token: ${{ secrets.GITHUB_TOKEN }}

    # Report coverage
    - name: Report coverage
      uses: zgosalvez/github-actions-report-lcov@v1
      with:
        artifact-name: 'Test coverage: nhost_graphql_adapter'
        coverage-files: packages/nhost_graphql_adapter/coverage/*.info
        working-directory: packages/nhost_graphql_adapter/
        github-token: ${{ secrets.GITHUB_TOKEN }}
